# This dockerfile is specific to building Multus for OpenShift
FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder
ADD . /usr/src/multus-cni
WORKDIR /usr/src/multus-cni
ENV CGO_ENABLED=1
ENV GO111MODULE=on
ENV GOFLAGS=-mod=readonly
ENV VERSION=rhel9 COMMIT=unset
RUN GO111MODULE=on go mod vendor && ./hack/build-go.sh && \
       cd /usr/src/multus-cni/bin
ENV GO111MODULE=on
RUN make build-e2e-tests && gzip -9 test/bin/multus-cni-tests-ext
WORKDIR /

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9
RUN dnf install -y util-linux && dnf clean all && \
       mkdir -p /usr/src/multus-cni/images && \
       mkdir -p /usr/src/multus-cni/bin
COPY --from=builder /usr/src/multus-cni/bin /usr/src/multus-cni/bin
COPY --from=builder /usr/src/multus-cni/test/bin/multus-cni-tests-ext.gz /usr/bin/multus-cni-tests-ext.gz
ADD ./images/entrypoint.sh /

LABEL io.k8s.display-name="Multus CNI" \
      io.k8s.description="This is a component of OpenShift Container Platform and provides a meta CNI plugin." \
      io.openshift.tags="openshift" \
      maintainer="Doug Smith <dosmith@redhat.com>"

ENTRYPOINT ["/entrypoint.sh"]
